server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:logiflow_db}
spring.datasource.username=${PGUSER:igor_dev}
spring.datasource.password=${PGPASSWORD:xa695FzKTQ6uPPU#}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html